eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#zuul:
#  routes:
#    api:
#      path: /api/**
#      serviceId: eurekaclient

management:
  security:
    enabled: false
zuul:
  routes:
    eurekaclient:
      path: /api1/**
      service: eurekaclient
    feign:
      path: /api2/**
      service: feign