eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
spring:
  application:
    name: feign
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#开启熔断器
feign:
  hystrix:
    enabled: true
management:
  security:
    #关闭安全验证
    enabled: false